### ISSUE TITLE
generate_emu_config Failed To Generate Controller Configuration Files For Magicka 2 (238370)

### ISSUE THREAD

**Issue by christantoan** [Detanup01/gbe_fork#40]
Here's the console output:
```
********* generating info for app id 238370 *********
App name on store: 'Magicka 2'
output dir: 'output\238370'
downloading app details in: output\238370\info\app_details.json
finding achievements stats...
downloading achievements images inside 'output\238370\steam_settings\img', images count = 94
finished downloading achievements images
downloading controller vdf files
downloading controller data, file id = 551563382, controller type = controller_steamcontroller_gordon
controller type is supported
Unexpected error:
(0, 'inputs')
-----------------------
Traceback (most recent call last):

  File "generate_emu_config.py", line 1060, in <module>

  File "generate_emu_config.py", line 948, in main

  File "controller_config_generator\parse_controller_vdf.py", line 105, in generate_controller_config

  File "controller_config_generator\parse_controller_vdf.py", line 32, in add_input_bindings

  File "vdf\vdict.py", line 87, in __getitem__

KeyError: (0, 'inputs')

-----------------------
```
Workaround is to use `-skip_con` switch.

**Comment by Detanup01** [comment]
should have been fixed in f7fe813310f1adc90fba7063ba798cca71db6a36
