### ISSUE TITLE
generate_emu_config.exe not working anymore

### ISSUE THREAD

**Issue by Gramaki** [Detanup01/gbe_fork#58]
For example, after running 'generate_emu_config.exe 1817190' in cmd, 2FA doesn't show up anymore. It worked normally before but now nothing happens.

**Comment by FeyrisTan** [comment]
Oh great I'm not the only one. Happens to me since yesterday. At first I thought it was because of mullvad but even with mullvad-exclude it does not quiet work. After a lot of tries it worked once but that was the only time. I do have 2FA.

**Comment by Detanup01** [comment]
Steam issue, even sometimes happened to DepotDownloader and currently fucked up with steam mobile too.

Our issue is Steampy is old and not maintained.
Might soon move that outside of goldberg and have it's own repo.

**Comment by Gramaki** [comment]
Aha got it, i thought it was maybe cause i was using older version from a year ago but when i downloaded latest one same thing was happening. I tried to generate steam settings via GSE Generator but i wasn't able to make it work with achievement watcher...

**Comment by Gramaki** [comment]
Aha got it, i thought it was maybe cause i was using older version from a year ago but when i downloaded latest one same thing was happening. I tried to generate steam settings via GSE Generator but i wasn't able to make it work with achievement watcher...

**Comment by God-damnit-all** [comment]
This is so annoying. I wish I could just set a Steam API key or something and be done with it.

**Comment by HarryMuscle** [comment]
Anyone know of any alternate tools that can be used to generate the emulator configuration?  Some of the files are easy to create manually but the achievement images and the achievements.json file really need a tool of some sorts to generate.

**Comment by Gramaki** [comment]
There's [GSE-Generator](https://github.com/brunolee-GIT/GSE-Generator) , but for some reason achievement watcher only works with steam settings folder that's been generated by generate_emu_config, tried to set it up with the one from gse generator but it's not working... Maybe you will make it work.

**Comment by DumbCodeGenerator** [comment]
Please, make "generate config tool" use [this fork](https://github.com/solsticegamestudios/steam) instead of original steampy

I edited python script to use it and have no problems. Also it saves your credentials(manually, but better than nothing), so you don't have to relogin every time

**Comment by God-damnit-all** [comment]
> Please, make "generate config tool" use [this fork](https://github.com/solsticegamestudios/steam) instead of original steampy
> 
> I edited python script to use it and have no problems. Also it saves your credentials(manually, but better than nothing), so you don't have to relogin every time

@Detanup01 I can confirm @DumbCodeGenerator's proposed fix works.

**Comment by FeyrisTan** [comment]
Don't we already have this?
[](https://github.com/Detanup01/gbe_fork/pull/57)

**Comment by FeyrisTan** [comment]
[https://github.com/Detanup01/gbe_fork/pull/57](url)

**Comment by Detanup01** [comment]
Future of this would be moving out this tool into a 3rd party one.
I probably gonna move it into C# and Steamkit since those are reliable than python and pip.
Until you have to do it manually, sorry.
Also can you confirm #57 works so in the meantime I can create a release for this?

**Comment by Gramaki** [comment]
I tested alex47exe's generator_emu_config from [#60](https://github.com/Detanup01/gbe_fork/issues/60) and it was working with achievement watcher. It generates everything without any issues.

**Comment by DogancanYr** [comment]
> I tested alex47exe's generator_emu_config from [#60](https://github.com/Detanup01/gbe_fork/issues/60) and it was working with achievement watcher. It generates everything without any issues.

This is the patch, but I don't know why it wasn't released.

https://github.com/Detanup01/gbe_fork/pull/57

**Comment by alex47exe** [comment]
> This is the patch, but I don't know why it wasn't released.
> 
> #57

Not sure why as well. Seems to be working without any issues. Hence I decided to include the fix in my fork a few days ago:
[https://github.com/alex47exe/gse_fork/releases](https://github.com/alex47exe/gse_fork/releases)

**Comment by God-damnit-all** [comment]
In the latest gbe_fork I'm getting:
```
Unknown exception: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=IRemovedMyAccountNameFromThisException (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6B8E0BBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')), maybe some account info is wrong?
Unexpected error:
name 'exit' is not defined
```

The compilation that was made from #57 is working but is no longer possible to recompile because https://github.com/Sak32009/steam_py_fork has been deleted.

**Comment by God-damnit-all** [comment]
Okay. Suddenly it's working now. I'm not sure why, I didn't change anything.

I think steam_py still needs to be tweaked, whatever @Sak32009 changed made it consistently work.

* * *

Here's the full Traceback in case it helps:
<details>
<summary>Traceback</summary>

```
Unknown exception: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=IRemovedMyAccountNameFromThisLog (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6B8E0BBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')), maybe some account info is wrong?
Unexpected error:
name 'exit' is not defined
-----------------------
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 72, in create_connection
  File "socket.py", line 976, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 716, in urlopen
  File "urllib3\connectionpool.py", line 404, in _make_request
  File "urllib3\connectionpool.py", line 1061, in _validate_conn
  File "urllib3\connection.py", line 363, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002D6B8E0BBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 802, in urlopen
  File "urllib3\util\retry.py", line 594, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=IRemovedMyAccountNameFromThisLog (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6B8E0BBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_emu_config.py", line 779, in main
  File "steam\webauth.py", line 377, in cli_login
  File "steam\webauth.py", line 311, in login
  File "steam\webauth.py", line 225, in _startLoginSession
  File "steam\webauth.py", line 179, in _encrypt_password
  File "steam\webauth.py", line 171, in _get_rsa_key
  File "steam\webauth.py", line 160, in send_api_request
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 700, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /IAuthenticationService/GetPasswordRSAPublicKey/v1?account_name=IRemovedMyAccountNameFromThisLog (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6B8E0BBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_emu_config.py", line 1087, in <module>
  File "generate_emu_config.py", line 782, in main
NameError: name 'exit' is not defined
-----------------------
```
</details>
